import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next and is not ours to lint. Neither is
    // anything under public/pdfjs or public/tesseract: those are pdf.js's and
    // tesseract.js's own files, vendored so the browser fetches them from this
    // origin instead of a CDN, and they are minified third-party bundles.
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "next-env.d.ts",
      "public/pdfjs/**",
      "public/tesseract/**",
    ],
  },
];

export default eslintConfig;
